name: ThinkPad T14s Gen 6 (Snapdragon)
arch: aarch64
pacman:
  install:
    - linux-t14s
    - linux-t14s-headers
    - t14s-firmware
    - fastfetch
    - mesa=1:24.2.0-1
    - libva-mesa-driver=1:24.2.0-1
    - mesa-vdpau=1:24.2.0-1
    - opencl-clover-mesa=1:24.2.0-1
    - vulkan-mesa-layers=1:24.2.0-1
    - vulkan-swrast=1:24.2.0-1
    - vulkan-freedreno=1:24.2.0-1
+also:
  - os/archlinuxarm
  - packages/openssh
  - packages/network-manager
  - packages/systemd-networkd
  - packages/editor
  - packages/bluez
  - repo/linux-t14s
  - shell/bash
  - desktop/plasma
  - common/pacman-init
