name: Snapdragon X1E Laptops
arch: aarch64
pacman:
  install:
    - linux-x1e
    - linux-x1e-headers
    - x1e-firmware
    - fastfetch
    - mesa
    - opencl-clover-mesa
    - vulkan-mesa-layers
    - vulkan-swrast
    - vulkan-freedreno
+also:
  - os/archlinuxarm
  - packages/openssh
  - packages/network-manager
  - packages/systemd-networkd
  - packages/editor
  - packages/bluez
  - repo/linux-x1e
  - shell/bash
  - desktop/plasma
  - common/pacman-init
filesystem:
  files:
  - path: /etc/kernel/cmdline
    content: |
      module_blacklist=qcom_edac,qcom_q6v5_pas efi=novamap pd_ignore_unused clk_ignore_unused fw_devlink=off cma=128M rootwait root=PARTLABEL=linux rootfstype=ext4 rootflags=noatime,discard rw loglevel=7
